services:
  isaac_sim_500:
    image: nvcr.io/nvidia/isaac-sim:5.0.0
    # runtime: nvidia
    user: root
    environment:
      - DISPLAY=${DISPLAY}
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./assets/500/cache/ov:/root/.cache/ov
      - ./assets/500/cache/pip:/root/.cache/pip
      - ./assets/500/cache/glcache:/root/.cache/nvidia/GLCache
      - ./assets/500/cache/computecache:/root/.nv/ComputeCache
      - ./assets/500/cache/asset_browser:/isaac-sim/exts/isaacsim.asset.browser/cache
      - ./assets/500/logs:/root/.nvidia-omniverse/logs
      - ./assets/500/data:/root/.local/share/ov/data
      - ./assets/500/pkg:/root/.local/share/ov/pkg
      - ./assets/500/documents:/root/Documents
    container_name: documentsocker_isaac_sim_500
    entrypoint: ["./runapp.sh"]

  isaac_sim_455:
    image: nvcr.io/nvidia/isaac-sim:4.5.0
    # runtime: nvidia
    user: root
    environment:
      - DISPLAY=${DISPLAY}
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./assets/450/cache/ov:/root/.cache/ov
      - ./assets/450/cache/pip:/root/.cache/pip
      - ./assets/450/cache/glcache:/root/.cache/nvidia/GLCache
      - ./assets/450/cache/computecache:/root/.nv/ComputeCache
      - ./assets/450/cache/asset_browser:/isaac-sim/exts/isaacsim.asset.browser/cache
      - ./assets/450/logs:/root/.nvidia-omniverse/logs
      - ./assets/450/data:/root/.local/share/ov/data
      - ./assets/450/pkg:/root/.local/share/ov/pkg
      - ./assets/450/documents/ments:/root/Documents
    container_name: docker_isaac_sim_455
    entrypoint: ["./runapp.sh"]

